import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const nunitoSans = Nunito_Sans({ subsets: ['cyrillic']});

export const metadata = {
  title: 'ITX',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta
            name="description"
            content="ITX"
          />
          <meta 
          name="keywords"
          content="internet, radio internet, wifi, radio, business wifi"/>
      <body className={nunitoSans.className}>{children}</body>
    </html>
  )
}
