'use client';
import './globals.css';
import { Nunito_Sans } from 'next/font/google'
import { useTheme } from 'next-themes';
import {useEffect} from 'react';

const nunitoSans = Nunito_Sans({ subsets: ['latin']});

export const metadata = {
  title: 'ITX Telecoms',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <meta 
        name="keywords"
        content="internet, radio internet, wifi, radio, business wifi"/>
      <body className={nunitoSans.className}>{children}</body>
    </html>
  )
}
