'use client';
import './globals.css';
import { Nunito_Sans } from 'next/font/google'
import { QueryClient, QueryClientProvider } from 'react-query';

const nunitoSans = Nunito_Sans({ subsets: ['latin']});

export const metadata = {
  title: 'ITX Telecoms',
  description: 'Generated by create next app',
}
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retryDelay: 1500,
      retry: true
    }
  }
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <meta 
        name="keywords"
        content="internet, radio internet, wifi, radio, business wifi"/>
      <body className={nunitoSans.className}>{children}</body>
      </QueryClientProvider>
    </html>
  )
}
